### ISSUE TITLE
Multi-monitor behavior

### ISSUE THREAD

**Issue by faassen** [rtts/ialauncher#4]
This is a cool project! My son and I came across it at the library today, thanks for setting it up!

I just tried this with a multi-monitor setup with Fedora under X11, nvidia drivers. I have two pieces of feedback:

The launcher ran but it started up with a very small window indeed. I could enlarge the window, but it would be nicer if it could be bigger right away, or possibly just full-screen.

When I start a dosbox game, somehow all 3 monitors start showing the same information. When I quit dosbox, I lost my multiple desktop setup and end up with 3 mirrored monitors.

Is this a deliberate feature to support multiple monitor presentation mode? If so, I think that should be behind a particular configuration option.

**Comment by faassen** [comment]
I just tested `dosbox -fullscreen` by itself, and for some reason this is the default behavior of dosbox on my machine. So this doesn't appear to be an issue with ialauncher itself. I'll dig in further to see whether I can determine the cause.

**Comment by JaapJoris** [comment]
Just a heads up, I have just released a new version which is based on SDL rather than WebKit. It's much faster and supports all operating systems out of the box.

It still calls `dosbox --fullscreen` though, so in order to get that working properly you probably have to fiddle with your DOSBox configuration file.
